### ISSUE TITLE
Mauvais nom de répo

### ISSUE THREAD

**Issue by lvanasse** [clubcapra/capra_estop#1]
Si on veut que ça soit robot agnostique, il faut que ce répo soit `capra_estop` au lieu de `markhor` qui est le robot qu'on a en ce moment, mais il avait `takin` avant ça.

**Comment by Zakmh2023** [comment]
Ah d'accord!! Je vais corriger ça!

Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
________________________________
From: Ludovic Vanasse ***@***.***>
Sent: Wednesday, September 22, 2021 9:23:02 AM
To: clubcapra/markhor_estop ***@***.***>
Cc: Murray-Hénault, Zakary ***@***.***>; Assign ***@***.***>
Subject: [clubcapra/markhor_estop] Mauvais nom de répo (#1)


Si on veut que ça soit robot agnostique, il faut que ce répo soit capra_estop au lieu de markhor qui est le robot qu'on a en ce moment, mais il avait takin avant ça.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclubcapra%2Fmarkhor_estop%2Fissues%2F1&data=04%7C01%7Czakary.murray-henault.1%40ens.etsmtl.ca%7C6880af52797d4c3c815908d97dcc1b44%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C637679137849881263%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kSsrNHnfR3JSOg5i%2FaGfPntKtnGvNCUm3CpmSZemzE4%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU32O64OZGWT7AEI7UDQ4J3UDHKDNANCNFSM5ERKDCFQ&data=04%7C01%7Czakary.murray-henault.1%40ens.etsmtl.ca%7C6880af52797d4c3c815908d97dcc1b44%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C637679137849891272%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2GCs8ifzN5muR2kX82Pa9f0eZIswZK0oyyzyK8QQn10%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Czakary.murray-henault.1%40ens.etsmtl.ca%7C6880af52797d4c3c815908d97dcc1b44%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C637679137849901265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bAoU1bIxF%2F0anveu6lmCeciyZFilGPCTvSIfwzOagGg%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Czakary.murray-henault.1%40ens.etsmtl.ca%7C6880af52797d4c3c815908d97dcc1b44%7C70aae3b79f3b484d8f9549e8fbb783c0%7C0%7C0%7C637679137849901265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fnq2k65oWI6z2YokKpkCxldbt6rwQf%2Bt3pnDOr7%2FG8Y%3D&reserved=0>.
